# Generated by Django 4.1.4 on 2022-12-30 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_brand_description_alter_carimage_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='short_description',
            field=models.CharField(default='Описание отсутсвует', max_length=100, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(upload_to='media/', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='car',
            name='photo',
            field=models.ImageField(upload_to='media/', verbose_name='Фотография авто'),
        ),
    ]
