# Generated by Django 4.1.4 on 2023-02-15 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0011_alter_carnote_content_alter_carnote_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carnote',
            name='content',
            field=models.TextField(blank=True, default='', null='', verbose_name='Содержание'),
        ),
    ]
