# Generated by Django 4.1.4 on 2023-02-15 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0013_alter_carimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carimage',
            name='description',
            field=models.CharField(blank=True, default='', max_length=70, null='', verbose_name='Описание'),
        ),
    ]
