# Generated by Django 4.1.4 on 2023-02-15 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0014_alter_carimage_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='carnote',
            name='description',
            field=models.CharField(blank=True, default='', max_length=70, null='', verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='carnote',
            name='image',
            field=models.ImageField(blank=True, default='plug.jpg', null='', upload_to='', verbose_name='Картинка'),
        ),
        migrations.DeleteModel(
            name='CarImage',
        ),
    ]
